version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - gateway

  gateway:
    build: ./backend/gateway
    ports:
      - "8080:8080"
    depends_on:
      - chat-service
      - portfolio-service

  chat-service:
    build: ./backend/chat-service
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PORT=3001
    volumes:
      - ./backend/chat-service:/app
      - /app/node_modules

  portfolio-service:
    build: ./backend/portfolio-service
    environment:
      - PORT=3002
    volumes:
      - ./backend/portfolio-service:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - gateway